packages:
  - "packages/*"

catalog:
  "@sveltejs/adapter-auto": ^7.0.1
  "@sveltejs/kit": ^2.53.4
  "@sveltejs/vite-plugin-svelte": ^7.0.0
  svelte: ^5.53.6
  "@typescript/native-preview": latest
  svelte-check: 4.4.4
  typescript: ^5.0.0
  vite: ^7.3.1
